//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbBrowser.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyRelation
    {
        public int Id { get; private set; }
        public FamilyRelationType ParentType { get; set; }
    
        public virtual StudentParent StudentParent { get; set; }
        public virtual Student Student { get; set; }
    }
}
