//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbBrowser.Data.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniversityDataBaseContainer : DbContext
    {
        public UniversityDataBaseContainer()
            : base("name=UniversityDataBaseContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StudentParent> StudentParents { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudyGroup> StudyGroups { get; set; }
        public virtual DbSet<Privilege> Privileges { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<FamilyRelation> FamilyRelations { get; set; }
    }
}
